### PR TITLE
Fix: replace title in add_fetch with student_name

### LINKED ISSUE #95: Error while adding sibling details in student
1.While adding a sibling in a student we got this error :- 

image

### PR DESCRIPTION
**Pull request by vr-greycube**
Fixes #95 
title cannot be used in add_fetch, so use student_name instead

### CODE REVIEW

File: education/education/doctype/student_group/student_group.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-cur_frm.add_fetch('student', 'title', 'student_name');
+cur_frm.add_fetch('student', 'student_name', 'student_name');
```
Comment (pateljannat) [inline education/education/doctype/student_group/student_group.js]: can you replace cur_frm with frm?
